---
- hosts: webservers
  become: true
  vars:
    http_host: "mydomain.local"
    http_conf: "my_domain.conf"
    http_port: "80"
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Create document root for your domain
      file:
        path: "/var/www/california"
        state: directory
        owner: "www-data"
        mode: '0755'
    - name: Copy california files
      copy:
        src: "/root/php_files/"
        dest: "/var/www/html/"

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
